### ISSUE TITLE
_ (underscore) denied as "Invalid character"

### ISSUE THREAD

**Issue by the-eater** [christoabrown/group-ironmen#1]
Hello,

I was trying to use your project, but I am unable to, because every time I enter my username, it'll throw the error "Invalid character" even tho, as shown here, it's a completely valid username :(
![A screenshot showing the name 'e_ter' in the chat field](https://user-images.githubusercontent.com/1922630/166109384-969e16b4-2b50-4c47-ad25-dfd38d47f0f4.png)

**Comment by christoabrown** [comment]
Oops, didn't know underscore was allowed in player names. I fixed it in 42ef8f9930d180466732a3805c0686b8ac5a8d8c. You may need to clear your cache on the site to see the change (ctrl + f5 usually).

**Comment by the-eater** [comment]
That was _very_ fast! thanks :)
