### ISSUE TITLE
Shared bank

### ISSUE THREAD

**Issue by Arachonage** [christoabrown/group-ironmen#13]
Love the tracker so far! The @shared doesnt seem to work though, or is there any way to sync it? Also saw that things like POH storage and collection log are still work in progress? Keep up the good work!

**Comment by Arachonage** [comment]
Nvm, shared bank just popped up, guess it needed some time ;)

**Comment by christoabrown** [comment]
Shared bank data gets uploaded whenever it gets saved so if nothing is deposited/withdrawn and it gets closed then it won't send any updates.
