### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Aer3x** [christoabrown/group-ironmen#17]
site doesn't come up after latest commit

Has it to do with this?

```
    "start": "concurrently \"npm run watch\" \"npm run serve -- --backend https://groupiron.men\"",
    "start:local-api": "concurrently \"npm run watch\" \"npm run serve -- --backend http://localhost:8080\"",
```

**Comment by Aer3x** [comment]
Installed a fresh one on a new machine, page offline.

**Comment by Aer3x** [comment]
group-ironmen-tracker-frontend  | No backend argument provided to dev server
group-ironmen-tracker-frontend  | [entrypoint] Replacing the API URL with the given HOST_URL
group-ironmen-tracker-frontend  | [entrypoint] Running bundle
group-ironmen-tracker-frontend  |
group-ironmen-tracker-frontend  | > group-ironmen@1.0.0 bundle
group-ironmen-tracker-frontend  | > npm run clean && node build.js --prod && node scripts/hash.js
group-ironmen-tracker-frontend  |
group-ironmen-tracker-frontend  |
group-ironmen-tracker-frontend  | > group-ironmen@1.0.0 clean
group-ironmen-tracker-frontend  | > node scripts/clean.js
group-ironmen-tracker-frontend  |
group-ironmen-tracker-frontend  | Production mode is enabled
group-ironmen-tracker-frontend  |
group-ironmen-tracker-frontend  | Build started
group-ironmen-tracker-frontend  | Minifying app.js
group-ironmen-tracker-frontend  | Build finished in 847.3ms
group-ironmen-tracker-frontend  | [entrypoint] Running serve
group-ironmen-tracker-frontend  |
group-ironmen-tracker-frontend  | > group-ironmen@1.0.0 serve
group-ironmen-tracker-frontend  | > node scripts/server.js
group-ironmen-tracker-frontend  |
group-ironmen-tracker-frontend  | No backend argument provided to dev server

**Comment by christoabrown** [comment]
made a change in 6e0a127354a842cc1d41c6ae85260954bff78a72 which should resolve this

**Comment by Aer3x** [comment]
> made a change in [6e0a127](https://github.com/christoabrown/group-ironmen/commit/6e0a127354a842cc1d41c6ae85260954bff78a72) which should resolve this

Yep, that did fix it.

Thanks for your work, it's a really cool and useful tool for our group.
