### ISSUE TITLE
Improve server container runtime

### ISSUE THREAD

**Issue by andrewf1** [christoabrown/group-ironmen#19]
The runtime of the server container after pulling the image is too long. It shouldn't be compiling on execution of the container. The container should just run the application and not worry about compiling the software as well. The image should should compile the code and the entrypoint should just run the binary.

I believe the reason this is done is because the application expects the secrets to be given at compile-time rather than runtime. The source would have to be updated to have the secrets injected as an environment variable or a configuration property.

[`pub const SECRET: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/secret"));`](https://github.com/christoabrown/group-ironmen/blob/b3d6fc4d347269fd60ae84cc528596a44ae9b65f/server/src/crypto.rs#L4)

**Comment by christoabrown** [comment]
done with c067d33bfb94d3c3635fdf786843218a16aadac9
