### ISSUE TITLE
broken after latest commit

### ISSUE THREAD

**Issue by Aer3x** [christoabrown/group-ironmen#28]
group page keeps loading.
not working anymore.

**Comment by Aer3x** [comment]
Did a clean install and can't get it to work.
"Create a group" and "Go to Group" pages keep showing a loading image.

**Comment by Aer3x** [comment]
i see a reference to Debian 11 in your dockerfile,
tried with Debian 11, also not working.

`error while loading shared libraries: libssl.so.3`

**Comment by christoabrown** [comment]
Should be fixed with latest docker image 1ea9696965e841529d5cea803902d9b7319109a0

**Comment by Aer3x** [comment]
> Should be fixed with latest docker image [1ea9696](https://github.com/christoabrown/group-ironmen/commit/1ea9696965e841529d5cea803902d9b7319109a0)

That fixed my problem, thanks!
