### ISSUE TITLE
add (rudimentary) regular expression to items search

### ISSUE THREAD

**Issue by samverijdt** [christoabrown/group-ironmen#4]
a nice feature would be to be able to search for example:

`dharok|guthan|karil|ahrim|verac|torag` to get all barrows items, it'd be a nice fix until a proper tagging system is in place

`"flax"` `rune$` `^rune` to show only flax(no toadflax), magic runes and rune metal stuff respectively (dont really care about this, just another example)

**Comment by chrisleee** [comment]
Added in #5
